version: '2'

services:
  docker-demo-base:
    container_name: docker-demo-base
    build:
      context: docker/base
    image: mijndomein/docker-demo:base
    labels:
      - "traefik.enable=false"

  docker-demo-ui:
    depends_on:
      - docker-demo-base
    container_name: docker-demo-ui
    build:
      context: .
      dockerfile: Dockerfile-ui
    image: mijndomein/docker-demo-ui:latest

  docker-demo-api:
    depends_on:
      - docker-demo-base
    container_name: docker-demo-api
    build:
      context: .
      dockerfile: Dockerfile-api
    image: mijndomein/docker-demo-api:latest
    labels:
      - "traefik.enable=false"

  docker-demo-build:
    depends_on:
      - docker-demo-base
    container_name: docker-demo-build
    build:
      context: docker/build
    image: mijndomein/docker-demo:build
    volumes:
      - .:/var/www/app
      - ~/.composer:/var/www/.composer
    labels:
      - "traefik.enable=false"

  traefik:
    container_name: traefik-demo
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - "traefik.enable=false"
