version: '2'

services:
  docker-demo:
    volumes:
        - ./demo:/var/www/app/demo
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3050:80

  docker-demo-api:
    ports:
      - 3051:80
    networks:
      default:
        aliases:
         - api.service.consul
