version: '2'

services:
  docker-demo:
    volumes:
        - ./demo:/var/www/app/demo
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3050:80
    labels:
      - "traefik.backend=demo"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:demo.mijndomein.nl;"

  docker-demo-api:
    ports:
      - 3051:80
    networks:
      default:
        aliases:
         - date.service.dev
    labels:
      - "traefik.enable=false"
