---
parameters:
  title: hello world
  subTitle: demo
  dateApiService: http://date.service.dev
  healthy: true
  rabbitMQ:
    host:
    port:
    user:
    pass:
    vhost:
    queue:
    exchange:
